blog/urls.py
from django.urls import path, re_path
from . import views



app_name = 'blog'
urlpatterns = [
	
	# path('home/', views.home, name='home'),
	path('blog/', views.blog, name='blog'),
	path('about/', views.about, name='about'),
	# re_path('^login/$', views.user_login, name="login-page"),
	# re_path('^logout/$', views.user_logout, name="logout-page"),

]

machine_learning/urls.py
from django.urls import path
from . import views



app_name = 'machine-learning'
urlpatterns = [
	
	path('model-1/', views.model_1, name='model_1'),
	path('model-2/', views.model_2, name='model_2'),
	path('model-3/', views.model_3, name='model_3'),

]

website/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from blog import views as blog_views


urlpatterns = [
    path('idari/', admin.site.urls),
    path('', blog_views.base, name='base'),
    path('website/', include('blog.urls')),
    path('machine-learning/', include('machine_learning.urls')),
    path('accounts/login/', blog_views.user_login, name="login-page"),
    path('accounts/logout/', blog_views.user_logout, name="logout-page"),
    path('accounts/register/', blog_views.user_register, name="register-page"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}


<html lang='en'>
<head>
	<title>OriginAI | 2020 </title>

	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- 	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"> -->


	<link rel="icon" href="{% static 'images/favicon3.ico' %}">
	<link rel="stylesheet" href="{% static 'css/base.css' %}">


</head>
<body>
	<a href="{% url 'base' %}">
		<div class="header-image"></div>
	</a>

 	<div class='topnavbar'>

		<a href="{% url 'base' %}" class="{{ home_status }}">Home</a>
		<a href="{% url 'blog:blog' %}" class="{{ blog_status }}">Blog</a>
		<a href="{% url 'blog:about' %}" class="{{ about_status }}">About</a>	

 		
		<div class="dropdown">
			<button class="dropbtn" onclick="myFunction()">Machine Learning
				<i class="fa fa-caret-down"></i>
			</button>
			<div class="dropdown-content" id="myDropdown">
				<a class="{{ model_1_status }}" href="{% url 'machine-learning:model_1' %}">Text Preprocessing</a>
				<a class="{{ model_2_status }}" href="{% url 'machine-learning:model_2' %}">Customer Churn</a>
				<a class="{{ model_3_status }}" href="{% url 'machine-learning:model_3' %}">Titanic Survival</a>
			</div>
		</div>

 		<div class="topnavbar-right">
 			{% if user.is_authenticated %}
 				<h3>{{ user.username }}</h3>
 				<a href="{% url 'logout-page' %}">Log Out</a>
 			{% else %}
 				<a href="{% url 'register-page' %}">Register</a>
 				<a href="{% url 'login-page' %}">Log in</a>
 			{% endif %}
 			
 		</div>
 	</div>


	<div class="content">
		{% block content %}
		
			<div class="panel panel-jumbo">
				<h3 class="welcome">Welcome!</h3>
				{% if user.is_authenticated %}
					<p>Hi, {{ user.username }}</p>
					<p>Last Login: {{ user.last_login }}</p>
					<p>Registered at: {{ user.date_joined }}</p>
				{% else %}
					<p>This website was built to host some of the Machine Learning and Natural Langugage Processing projects which i implemented while i was learning the frameworks/libraries, and a separate blog page which i may update in the near future.</p> 
					<p>You need to <a href="{% url 'login-page' %}">login</a> or <a href="{% url 'register-page' %}">register</a> and then login to access the Machine Learning page.</p>
					<br />
					<p><b>username:</b> deneme, <b>password:</b>123456ai</p>
					
				{% endif %}
				  
			</div>

			<div class="panel panel-primary">
              <div class="panel-heading">Available Models</div>
	              <div class="panel-body">
	                <ol>
	                 	<li>Text Preprocessing - remove stopwords, special characters, numbers, html tags, url.</li>
	                 	<li>Telco Customer Churn - Predict if a customer will churn given the contract details.</li>
	                 	<li>Titanic Survival - Predict if a person survived after the crash.</li>
	                </ol>
	              </div>
            </div>
            
<!--             <img src="{% static 'images/main.jpg' %}" alt="Main Picture"> -->
			<br><br>
			
		{% endblock %}
		<button onclick="topFunction()" id="topBtn" title="Go to Top">Top</button>
	</div>

<script type="text/javascript">
// Dropdown Menu
/* When the user clicks on the button, toggle between hiding and showing the dropdown content */
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}


// Close the dropdown if the user clicks outside of it
window.onclick = function(e) {
  if (!e.target.matches('.dropbtn')) {
  var myDropdown = document.getElementById("myDropdown");
    if (myDropdown.classList.contains('show')) {
      myDropdown.classList.remove('show');
    }
  }
}
</script>

<script type="text/javascript">
// Top scroll button
topbutton = document.getElementById('topBtn');
window.onscroll = function() {scrollFunction()};

function scrollFunction(){
	if (document.body.scrollTop > 10 || document.documentElement.scrollTop > 10) {
		topbutton.style.display = "block";
	} else {
		topbutton.style.display = "none";
	}
}

function topFunction() {
	document.body.scrollTop = 0;
	document.documentElement.scrollTop = 0;
}
</script>

</body>
</html>